image: "python:3.9.16"

stages:
  - test

variables:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://localhost.localstack.cloud:4566
  CI_DEBUG_SERVICES: "true"
  DEBUG: 1
  LS_LOG: "trace"

default:
  services:
    - name: docker:20.10.21-dind-alpine3.17
      alias: docker
      command: ["--tls=false"]
    - name: localstack/localstack:latest
      alias: localhost.localstack.cloud
      variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
        DOCKER_TLS_VERIFY: "false"
  before_script:
    - apt-get update && apt-get install -y zip jq
    - pip install -r requirements-dev.txt

test:
  stage: test
  allow_failure: true
  script:
    - ./bin/deploy.sh
    - pytest tests
