image: "python:3.9.16"

stages:
  - deploy
  - test

services:
  - name: docker:20.10.21-dind-alpine3.17
    alias: docker
    command: ["--tls=false"]
  - name: localstack/localstack:latest
    alias: localstack
    variables:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""

variables:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://localstack:4566
  CI_DEBUG_SERVICES: "true"

default:
  before_script:
    - apt-get update && apt-get install -y zip jq
    - pip install -r requirements-dev.txt

deploy:
  stage: deploy
  script:
    - ./bin/deploy.sh

# test:
#   stage: test

#   script:
#     - ./bin/deploy.sh