image: docker:24.0.7-dind-alpine3.18 # Alpine 3.18's repo contains by default Python v3.11.8

stages:
  - deploy
  - test

variables:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  AWS_DEFAULT_REGION: us-east-1
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://localhost.localstack.cloud:4566
  PIP_CACHE_DIR: $CI_PROJECT_DIR/.cache/pip
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  DEBUG: 1
  LS_LOG: trace
  LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT: 300

services:
  - name: docker:24.0.7-dind-alpine3.18
    alias: docker
    command: ["--tls=false"]

default:
  before_script: &default_before_scripts
    - apk update
    - apk add --no-cache gcc musl-dev linux-headers bash zip jq curl py3-psutil python3
    - python3 -m ensurepip
    - python3 -m pip install --no-cache --upgrade pip setuptools
    - mkdir -p $PIP_CACHE_DIR
    - python3 -m pip install localstack awscli awscli-local
    - docker pull localstack/localstack-pro:latest
    # Gitlab has changed to ipv6, but LocalStack not supporting it
    - dind_ip="$(getent ahostsv4 docker | cut -d' ' -f1 | head -n1)"
    - echo -e "${dind_ip}\tlocalhost.localstack.cloud\n" >> /etc/hosts
    - localstack start -d
    - localstack wait -t 30
    - (test -f ./ls-state-pod.zip && localstack state import ./ls-state-pod.zip) || true
  cache:
    paths:
      - $CI_PROJECT_DIR/.cache/pip
  artifacts:
    paths:
      - $CI_PROJECT_DIR/ls-state-pod.zip
    expire_in: 1 days

deploy:
  stage: deploy
  rules:
    - when: never
      changes:
        - ./*.md
        - LICENSE
        - .circleci/*
        - .github/*
    - when: always
  script:
    - ./bin/deploy.sh
    - localstack state export ./ls-state-pod.zip

test:
  stage: test
  rules:
    - when: never
      changes:
        - ./*.md
        - LICENSE
        - .circleci/*
        - .github/*
    - when: always
  needs:
    - deploy
  before_script:
    - *default_before_scripts
    - python3 -m pip install -r requirements-dev.txt
  script:
    - python3 -m pytest tests || (localstack logs && exit 1)
