version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    AWS_ACCESS_KEY_ID: test
    AWS_SECRET_ACCESS_KEY: test
  parameter-store:
    LOCALSTACK_AUTH_TOKEN: /CodeBuild/LOCALSTACK_AUTH_TOKEN
    GITHUB_PAT: /CodeBuild/GH_TOKEN
    GITHUB_PAT_GITHUB_COM: /CodeBuild/GH_TOKEN

phases:
  install:
    runtime-versions:
      python: 3.11
    steps:
      - run: |
          test -d /root/.pyenv/versions/3.9.16/bin || pyenv install 3.9.16
          pyenv global 3.9.16
      - run: pip install -r requirements-dev.txt
      - run: docker pull public.ecr.aws/localstack/localstack-pro:latest
      - run: docker image tag public.ecr.aws/localstack/localstack-pro:latest localstack/localstack-pro:latest
      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          image-tag: 'latest'
          use-pro: 'true'
          configuration: LS_LOG=trace
          install-awslocal: 'true'
      # - name: Load Pod
      #   uses: LocalStack/setup-localstack/cloud-pods@main
      #   with:
      #     name: codebuild-pod
      #     action: load
  pre_build:
    steps:
      - run: bin/deploy.sh
      - name: Save Pod
        uses: LocalStack/setup-localstack/cloud-pods@main
        with:
          name: codebuild-pod
          action: save
  build:
    commands:
      - pytest tests
    finally:
      - localstack logs

cache:
  paths:
    - /root/.pyenv/versions/3.9.16
