version: 2.1
orbs:
  localstack: localstack/platform@2.1
jobs:
  localstack-test:
    executor: localstack/default
    steps:
      - localstack/start
      - run:
          command: echo "Running my custom application initialization logic ..."
      - localstack/wait
      - run:
          command: echo "Now LocalStack has fully started up, and is ready to use!"
workflows:
  localstack-test:
    jobs:
      - localstack-test
