version: 2.1
orbs:
  localstack: localstack/platform@2.1
jobs:
  save-state:
    executor: localstack/default
    steps:
      - localstack/start        
      - checkout
      - run:
          name: Install dependencies
          command:
            pip3 install -r requirements-dev.txt
      - localstack/wait
      - run:
          name: Deploy infrastructure
          command:
            bin/deploy.sh
      - run:
          name: Export state
          command: localstack state export ls-state.zip
      - save_cache:
          paths:
            - ls-state.zip
          key: ls-state
      - save_cache:
          paths:
            - ~/.cache/pip
          key: python-deps
  load-state:
    executor: localstack/default
    environment:
        AWS_DEFAULT_REGION: us-east-1
        AWS_REGION: us-east-1
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
    steps:
      - restore_cache:
          key: python-deps
      - localstack/start        
      - checkout
      - run:
          name: Install dependencies
          command:
            pip3 install -r requirements-dev.txt
      - localstack/wait
      - restore_cache:
          key: ls-state
      - run:
          name: Import state
          command: test -f ls-state.zip && localstack state import ls-state.zip
      - run:
          name: Run Tests
          command:
            pytest tests
workflows:
  do-tests:
    jobs:
      - save-state
      - load-state:
          requires: [save-state]