name: Create PR Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - ./*.md
      - LICENSE
      - .circleci/*

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install awscli-local

      - name: Deploy Preview
        uses: LocalStack/setup-localstack@main
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          state-backend: ephemeral
          state-action: start
          include-preview: 'true'
          install-awslocal: 'true'
          preview-cmd: |
            # Add your custom deployment commands here. 
            # Below is an example for the Image resizer application.
            bin/build_lambdas.sh && deployment/awslocal/deploy.sh
