name: Finalize PR Preview

on:
  workflow_run:
    workflows: ["Create PR Preview"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Finalize PR comment
        uses: LocalStack/setup-localstack/finish@v0.2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          include-preview: true