name: Sync repo to Gitlab
on:
  workflow_dispatch:
  schedule:
    - cron: '15 20 * * *'

jobs:
  sync:
    name: Gitlab Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Mirroring Repository
        uses: fscarmen/repository-mirroring-action@v1.0.0
        with:
          target_repo_url: git@gitlab.com:localstack.cloud/samples/sample-serverless-image-resizer-s3-lambda.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
