name: Create and Test LocalStack State File

on:
  schedule:
    # At 00:00 on Saturday.
    - cron: "0 0 * * 6"
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  create-state-file:
    name: Create State Files
    runs-on: ubuntu-latest
    permissions:
      actions: write
    outputs:
      state_files_artifact_name: state-file-${{ github.run_id }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements-dev.txt --upgrade

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          use-pro: 'true'
          install-awslocal: 'true'
        env:
          DEBUG: 1
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Deploy Infrastructure (Example)
        run: |
          bin/build_lambdas.sh && deployment/awslocal/deploy.sh

      - name: Export LocalStack State File
        id: export_state
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: |
          echo "Exporting LocalStack state..."
          localstack state export state-file.zip
          ls -la state-file.zip # Verify the file exists
          echo "state_files_artifact_name=state-file-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Upload State File Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.export_state.outputs.state_files_artifact_name }}
          path: state-file.zip
          retention-days: 1

  test-state-file:
    name: Test State File
    needs: create-state-file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Test Dependencies
        run: |
          pip install -r requirements-dev.txt --upgrade

      - name: Start LocalStack
        uses: LocalStack/setup-localstack@main
        with:
          use-pro: 'true'
          install-awslocal: 'true'
        env:
          DEBUG: 1
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}

      - name: Download State File Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.create-state-file.outputs.state_files_artifact_name }}

      - name: Inject State File
        env:
          LOCALSTACK_AUTH_TOKEN: ${{ secrets.LOCALSTACK_AUTH_TOKEN }}
        run: |
          echo "Importing LocalStack state from state-file.zip..."
          ls -la # Check if download was successful
          localstack state import state-file.zip

      - name: Run Tests
        env:
          AWS_DEFAULT_REGION: us-east-1
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
        run: |
          pytest tests

      - name: Show LocalStack Logs
        if: always()
        run: |
          localstack logs

      - name: Send a Slack notification
        if: failure() || github.event_name != 'pull_request'
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          token: ${{ secrets.GITHUB_TOKEN }}
          notification_title: "{workflow} has {status_message}"
          message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
          footer: "Linked Repo <{repo_url}|{repo}> | <{run_url}|View Workflow run>"
          notify_when: "failure"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Generate a Diagnostic Report
        if: failure()
        run: |
          curl -s localhost:4566/_localstack/diagnose | gzip -cf > diagnose.json.gz

      - name: Upload the Diagnostic Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diagnose.json.gz
          path: ./diagnose.json.gz
